live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "Full"
opacity = 0.95
dynamic_title = true

[shell]
program = "tmux"

[font]
size = 14

[font.normal]
family = "Bitstream Vera Sans Mono"
style = "Regular"

[colors]

[colors.primary]
background = "#0A0E14"
foreground = "#eafbff"

[window.dimensions]
columns = 80
lines = 30

[colors.normal]
black = "#01060E"
red = "#EA6C73"
green = "#00E673"
yellow = "#F9AF4F"
blue = "#53BDFA"
magenta = "#FAE994"
cyan = "#90E1C6"
white = "#C7C7C7"

[colors.bright]
black = "#686868"
red = "#F07178"
green = "#C2D94C"
yellow = "#FFB454"
blue = "#59C2FF"
magenta = "#FFEE99"
cyan = "#95E6CB"
white = "#FFFFFF"
